class AppLanguage {
  const AppLanguage(this.code, this.native, {this.rtl = false});

  final String code;
  final String native;
  final bool rtl;
}

const appLanguages = <AppLanguage>[
  AppLanguage('en', 'English'),
  AppLanguage('ur', 'اردو', rtl: true),
  AppLanguage('ur_latn', 'Roman Urdu'),
  AppLanguage('hi', 'हिन्दी'),
  AppLanguage('ar', 'العربية', rtl: true),
  AppLanguage('ps', 'پښتو', rtl: true),
  AppLanguage('sd', 'سنڌي', rtl: true),
  AppLanguage('bal', 'بلوچی', rtl: true),
  AppLanguage('es', 'Español'),
];

AppLanguage? languageByCode(String code) {
  for (final language in appLanguages) {
    if (language.code == code) return language;
  }
  return null;
}

/// Menu and everyday labels for languages other than English and Urdu.
/// Missing keys fall back to English.
const languagePacks = <String, Map<String, String>>{
  'ur_latn': {
    'dashboard': 'Dashboard',
    'selling': 'Farokht',
    'stockPurchases': 'Stock aur khareedari',
    'money': 'Raqam',
    'team': 'Team aur settings',
    'pos': 'POS terminal',
    'products': 'Products',
    'categories': 'Categories',
    'brands': 'Brands',
    'units': 'Units',
    'manufacturing': 'Manufacturing',
    'stock': 'Stock',
    'ledger': 'Inventory ledger',
    'transfers': 'Stock transfer',
    'adjustment': 'Stock adjustment',
    'writeOff': 'Stock write-off',
    'locationMove': 'Godown move',
    'purchases': 'Khareedari',
    'sales': 'Farokht',
    'customers': 'Gahak aur supplier',
    'expenses': 'Akhrajat',
    'accounts': 'Khate',
    'roznamcha': 'Roznamcha',
    'investment': 'Sarmaya',
    'cheques': 'Cheques',
    'reports': 'Reports',
    'hr': 'HR',
    'settings': 'Settings',
    'branches': 'Branches',
    'users': 'Users',
    'allBranches': 'Tamam branches',
    'logout': 'Log out',
    'synced': 'Sync ho gaya',
    'offline': 'Offline',
    'pendingSync': 'Sync baqi hai',
    'search': 'Talash',
    'save': 'Mehfooz karein',
    'add': 'Shamil karein',
    'cancel': 'Mansookh',
    'delete': 'Hataein',
    'edit': 'Tabdeel',
    'language': 'Zaban',
    'recentSales': 'Haaliya farokht',
    'estimates': 'Andaaze',
    'saleOrders': 'Sale orders',
    'deliveryNotes': 'Delivery notes',
    'creditRecovery': 'Udhaar wasooli',
    'areas': 'Ilaqe',
    'employees': 'Mulazimeen',
    'attendance': 'Hazri',
    'salaries': 'Tankhwahen',
    'paymentMethods': 'Payment ke tareeqe',
    'bankAccounts': 'Bank accounts',
    'dailyBook': 'Rozana kitab',
    'dayClose': 'Din band',
    'receivePurchase': 'Khareedari wasool karein',
    'purchaseOrders': 'Khareed orders',
    'returnsRegister': 'Wapsi register',
    'partyReport': 'Party report',
  },
  'hi': {
    'dashboard': 'डैशबोर्ड',
    'selling': 'बिक्री',
    'stockPurchases': 'स्टॉक और खरीद',
    'money': 'पैसा',
    'team': 'टीम और सेटिंग्स',
    'pos': 'POS टर्मिनल',
    'products': 'उत्पाद',
    'categories': 'श्रेणियाँ',
    'brands': 'ब्रांड',
    'units': 'इकाइयाँ',
    'manufacturing': 'निर्माण',
    'stock': 'स्टॉक',
    'ledger': 'इन्वेंटरी खाता',
    'transfers': 'स्टॉक ट्रांसफर',
    'adjustment': 'स्टॉक समायोजन',
    'writeOff': 'स्टॉक राइट-ऑफ',
    'locationMove': 'गोदाम स्थानांतरण',
    'purchases': 'खरीद',
    'sales': 'बिक्री',
    'customers': 'ग्राहक और सप्लायर',
    'expenses': 'खर्च',
    'accounts': 'खाते',
    'roznamcha': 'रोजनामचा',
    'investment': 'निवेश',
    'cheques': 'चेक',
    'reports': 'रिपोर्ट',
    'hr': 'एचआर',
    'settings': 'सेटिंग्स',
    'branches': 'शाखाएँ',
    'users': 'उपयोगकर्ता',
    'allBranches': 'सभी शाखाएँ',
    'logout': 'लॉग आउट',
    'synced': 'सिंक हो गया',
    'offline': 'ऑफलाइन',
    'pendingSync': 'सिंक बाकी',
    'search': 'खोज',
    'save': 'सहेजें',
    'add': 'जोड़ें',
    'cancel': 'रद्द करें',
    'delete': 'हटाएँ',
    'edit': 'संपादित करें',
    'language': 'भाषा',
    'recentSales': 'हाल की बिक्री',
    'estimates': 'अनुमान',
    'saleOrders': 'बिक्री आदेश',
    'deliveryNotes': 'डिलीवरी नोट',
    'creditRecovery': 'उधार वसूली',
    'areas': 'क्षेत्र',
    'employees': 'कर्मचारी',
    'attendance': 'हाजिरी',
    'salaries': 'वेतन',
    'paymentMethods': 'भुगतान के तरीके',
    'bankAccounts': 'बैंक खाते',
    'dailyBook': 'दैनिक बही',
    'dayClose': 'दिन बंद',
    'receivePurchase': 'खरीद प्राप्त करें',
    'purchaseOrders': 'खरीद आदेश',
    'returnsRegister': 'वापसी रजिस्टर',
    'partyReport': 'पार्टी रिपोर्ट',
  },
  'ar': {
    'dashboard': 'لوحة التحكم',
    'selling': 'المبيعات',
    'stockPurchases': 'المخزون والمشتريات',
    'money': 'المال',
    'team': 'الفريق والإعدادات',
    'pos': 'نقطة البيع',
    'products': 'المنتجات',
    'categories': 'التصنيفات',
    'brands': 'العلامات',
    'units': 'الوحدات',
    'manufacturing': 'التصنيع',
    'stock': 'المخزون',
    'ledger': 'سجل المخزون',
    'transfers': 'تحويل المخزون',
    'adjustment': 'تسوية المخزون',
    'writeOff': 'شطب المخزون',
    'locationMove': 'نقل المستودع',
    'purchases': 'المشتريات',
    'sales': 'المبيعات',
    'customers': 'العملاء والموردون',
    'expenses': 'المصروفات',
    'accounts': 'الحسابات',
    'roznamcha': 'دفتر اليومية',
    'investment': 'الاستثمار',
    'cheques': 'الشيكات',
    'reports': 'التقارير',
    'hr': 'الموارد البشرية',
    'settings': 'الإعدادات',
    'branches': 'الفروع',
    'users': 'المستخدمون',
    'allBranches': 'كل الفروع',
    'logout': 'تسجيل الخروج',
    'synced': 'تمت المزامنة',
    'offline': 'غير متصل',
    'pendingSync': 'بانتظار المزامنة',
    'search': 'بحث',
    'save': 'حفظ',
    'add': 'إضافة',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'language': 'اللغة',
    'recentSales': 'المبيعات الأخيرة',
    'estimates': 'عروض الأسعار',
    'saleOrders': 'أوامر البيع',
    'deliveryNotes': 'إشعارات التسليم',
    'creditRecovery': 'تحصيل الآجل',
    'areas': 'المناطق',
    'employees': 'الموظفون',
    'attendance': 'الحضور',
    'salaries': 'الرواتب',
    'paymentMethods': 'طرق الدفع',
    'bankAccounts': 'الحسابات البنكية',
    'dailyBook': 'الدفتر اليومي',
    'dayClose': 'إقفال اليوم',
    'receivePurchase': 'استلام مشتريات',
    'purchaseOrders': 'أوامر الشراء',
    'returnsRegister': 'سجل المرتجعات',
    'partyReport': 'تقرير الأطراف',
  },
  'ps': {
    'dashboard': 'ډشبورډ',
    'selling': 'پلور',
    'stockPurchases': 'سټاک او پېرود',
    'money': 'پیسې',
    'team': 'ټیم او تنظیمات',
    'pos': 'POS ټرمینل',
    'products': 'محصولات',
    'categories': 'کټګورۍ',
    'brands': 'برانډونه',
    'units': 'واحدونه',
    'manufacturing': 'جوړونه',
    'stock': 'سټاک',
    'purchases': 'پېرود',
    'sales': 'پلور',
    'customers': 'پیرودونکي او عرضه کوونکي',
    'expenses': 'لګښتونه',
    'accounts': 'حسابونه',
    'reports': 'راپورونه',
    'settings': 'تنظیمات',
    'branches': 'څانګې',
    'users': 'کارنان',
    'allBranches': 'ټولې څانګې',
    'logout': 'وتل',
    'synced': 'همغږی شو',
    'offline': 'آفلاین',
    'pendingSync': 'همغږي پاتې ده',
    'search': 'لټون',
    'save': 'خوندي کړئ',
    'add': 'زیات کړئ',
    'cancel': 'لغوه',
    'language': 'ژبه',
  },
  'sd': {
    'dashboard': 'ڊيش بورڊ',
    'selling': 'وڪرو',
    'stockPurchases': 'اسٽاڪ ۽ خريداري',
    'money': 'رقم',
    'team': 'ٽيم ۽ سيٽنگون',
    'pos': 'POS ٽرمينل',
    'products': 'شيون',
    'categories': 'قسمون',
    'brands': 'برانڊ',
    'units': 'يونٽ',
    'stock': 'اسٽاڪ',
    'purchases': 'خريداري',
    'sales': 'وڪرو',
    'customers': 'گراهڪ ۽ سپلائر',
    'expenses': 'خرچ',
    'accounts': 'کاتا',
    'reports': 'رپورٽون',
    'settings': 'سيٽنگون',
    'branches': 'شاخون',
    'users': 'استعمال ڪندڙ',
    'allBranches': 'سڀ شاخون',
    'logout': 'لاگ آئوٽ',
    'synced': 'هم آهنگ ٿي ويو',
    'offline': 'آف لائن',
    'pendingSync': 'هم آهنگي باقي',
    'search': 'ڳولا',
    'save': 'محفوظ ڪريو',
    'add': 'شامل ڪريو',
    'cancel': 'رد',
    'language': 'ٻولي',
  },
  'bal': {
    'dashboard': 'ڈیش بورڈ',
    'selling': 'فروخت',
    'stockPurchases': 'اسٹاک و خرید',
    'money': 'زر',
    'team': 'ٹیم و سیٹنگ',
    'pos': 'POS ٹرمینل',
    'products': 'جنس',
    'stock': 'اسٹاک',
    'purchases': 'خرید',
    'sales': 'فروخت',
    'customers': 'گاہک و سپلائر',
    'expenses': 'خرچ',
    'accounts': 'حساب',
    'reports': 'رپورٹ',
    'settings': 'سیٹنگ',
    'branches': 'برانچ',
    'users': 'صارف',
    'allBranches': 'تمام برانچ',
    'logout': 'لاگ آؤٹ',
    'synced': 'ہم آہنگ بیت',
    'offline': 'آف لائن',
    'pendingSync': 'ہم آہنگی باقی',
    'search': 'گشت',
    'save': 'محفوظ کن',
    'add': 'شامل کن',
    'cancel': 'منسوخ',
    'language': 'زبان',
  },
  'es': {
    'dashboard': 'Panel',
    'selling': 'Ventas',
    'stockPurchases': 'Stock y compras',
    'money': 'Dinero',
    'team': 'Equipo y ajustes',
    'pos': 'Terminal POS',
    'products': 'Productos',
    'categories': 'Categorías',
    'brands': 'Marcas',
    'units': 'Unidades',
    'manufacturing': 'Fabricación',
    'stock': 'Stock',
    'ledger': 'Libro de inventario',
    'transfers': 'Transferencia',
    'adjustment': 'Ajuste de stock',
    'writeOff': 'Baja de stock',
    'locationMove': 'Movimiento de almacén',
    'purchases': 'Compras',
    'sales': 'Ventas',
    'customers': 'Clientes y proveedores',
    'expenses': 'Gastos',
    'accounts': 'Cuentas',
    'roznamcha': 'Libro diario',
    'investment': 'Inversión',
    'cheques': 'Cheques',
    'reports': 'Informes',
    'hr': 'RR. HH.',
    'settings': 'Ajustes',
    'branches': 'Sucursales',
    'users': 'Usuarios',
    'allBranches': 'Todas las sucursales',
    'logout': 'Cerrar sesión',
    'synced': 'Sincronizado',
    'offline': 'Sin conexión',
    'pendingSync': 'Pendiente de sincronizar',
    'search': 'Buscar',
    'save': 'Guardar',
    'add': 'Añadir',
    'cancel': 'Cancelar',
    'delete': 'Eliminar',
    'edit': 'Editar',
    'language': 'Idioma',
    'recentSales': 'Ventas recientes',
    'estimates': 'Presupuestos',
    'saleOrders': 'Pedidos de venta',
    'deliveryNotes': 'Albaranes',
    'creditRecovery': 'Cobro a crédito',
    'areas': 'Zonas',
    'employees': 'Empleados',
    'attendance': 'Asistencia',
    'salaries': 'Nóminas',
    'paymentMethods': 'Métodos de pago',
    'bankAccounts': 'Cuentas bancarias',
    'dailyBook': 'Libro diario',
    'dayClose': 'Cierre del día',
    'receivePurchase': 'Recibir compra',
    'purchaseOrders': 'Pedidos de compra',
    'returnsRegister': 'Registro de devoluciones',
    'partyReport': 'Informe de contactos',
  },
};
